name: "docker/kurento-buildpackage"

on:
  # Manual trigger.
  workflow_dispatch:
    inputs:
      jobDistros:
        description: "List of Ubuntu codenames"
        required: true
        type: string

        # There is no "list" type, so use a raw JSON array and `fromJson()`.
        #default: '["xenial", "bionic", "focal"]'
        default: '["focal"]'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobDistro: ${{ fromJson(github.event.inputs.jobDistros) }}
    steps:
      # Action: https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Add ci-scripts/ to PATH
        working-directory: ci-scripts/
        run: echo "$PWD" >>$GITHUB_PATH

      - name: Run job script
        env:
          PUSH_IMAGES: "yes"
          BUILD_ARGS: "UBUNTU_CODENAME=${{ matrix.jobDistro }}"
          TAG: "${{ matrix.jobDistro }}"
          TAG_COMMIT: "no"
        working-directory: docker/kurento-buildpackage/
        run: kurento_container_build.sh
