name: "000 (Template)"

on:
  # Manual trigger.
  workflow_dispatch:

  # Trigger from other job.
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World!"
