name: "server-buildpackage-rust.child"

on:
  # Triggered from other workflows.
  workflow_call:
    inputs:
      jobDistros:
        description: "List of Ubuntu codenames to build for"
        required: true
        # There is no `list` type, so use a raw JSON array and `fromJson()`.
        # Example: '["xenial", "bionic", "focal"]'
        type: "string"
        default: '["noble"]'
      jobGitRepo:
        description: "Git repo from where the Rust code is got to build package"
        required: false
        type: "string"
        default: "GStreamer/gst-plugin-rs"
      jobGitName:
        description: "Non-default git branch or tag that should be checked out, if it exists"
        required: false
        type: "string"
        default: "gstreamer-1.24.2"
      jobRelease:
        description: "Enable to build release versions; disable for development builds"
        required: false
        type: "boolean"
      runnerGroup:
        description: "runnerGroup: Set of runners where the workflow jobs should be run"
        required: false
        type: "string"
        default: "Linux"

jobs:
  build:
    runs-on: ["self-hosted", "${{ inputs.runnerGroup }}"]
    strategy:
      matrix:
        jobDistro: ${{ fromJson(inputs.jobDistros) }}
    timeout-minutes: 30
    steps:
      - name: "Check for non-default git ref"
        id: "git-ref"
        run: |
          if [[ -n "${{ inputs.jobGitName }}" ]]; then
            echo "value=${{ inputs.jobGitName }}" >>$GITHUB_OUTPUT
          else
            echo "value=main" >>$GITHUB_OUTPUT
          fi

      # Action: https://github.com/actions/checkout
      - name: "Checkout"
        uses: "actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c" # v3.3.0
        with:
          repository: "${{ inputs.jobGitRepo }}"
          ref: "${{ steps.git-ref.outputs.value }}"

      - name: "Configure the environment for ci-scripts/"
        run: |
          echo "$PWD/kurento/ci-scripts" >>$GITHUB_PATH
          echo "KURENTO_SCRIPTS_HOME=$PWD/kurento/ci-scripts" >>$GITHUB_ENV
          echo "GSTREAMER_RUST_PATCH_DIR=$PWD/kurento/server/gst-plugins-rs" >>$GITHUB_ENV
          echo "JOB_TIMESTAMP=$(date --utc +%Y%m%d%H%M%S)" >>$GITHUB_ENV

      - name: "Run job script"
        env:
          JOB_DISTRO: "${{ matrix.jobDistro }}"
          JOB_RELEASE: "${{ inputs.jobRelease }}"
          DISABLE_APT_PROXY: "true"
          INSTALL_PATH: "${{ steps.copy-artifacts.outputs.download-path }}"
        run: "ci_job_package_gst_rust_debian.sh"


      # Action: https://github.com/actions/upload-artifact
      - name: "Archive the artifacts"
        uses: "actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce" # v3.1.2
        with:
          name: "artifacts"
          path: "*.*deb"